In [1]:
import pandas as pd

In [4]:
df_from_json = pd.read_json("example-2.json")

df_from_json

   Column 1  Column 2
0         1         2
1         3         4
2         5         6

In [5]:
json_string = df_from_json.to_json()

json_string

'{"Column 1":{"0":1,"1":3,"2":5},"Column 2":{"0":2,"1":4,"2":6}}'

In [6]:
df_csv = pd.read_csv("example-1.csv")

df_csv

     Branch       Date  Amount
0  Branch A  January 1   500.0
1  Branch B  January 2   250.0
2  Branch A  January 3   300.0