In [1]:
import pandas as pd

In [2]:
df_one = pd.DataFrame(columns=["Column 1", "Column 2"])

df_one

Empty DataFrame
Columns: [Column 1, Column 2]
Index: []

In [3]:
df_one.columns = ["First", "Second"]

df_one

Empty DataFrame
Columns: [First, Second]
Index: []

In [6]:
new_data = {
    "First" : [1,2, "foo"],
    "Second" : [3,4, "bar"]
}

In [7]:
df_two = pd.DataFrame(new_data)

df_two

  First Second
0     1      3
1     2      4
2   foo    bar

In [8]:
df_combined = pd.concat([df_one, df_two])

df_combined

  First Second
0     1      3
1     2      4
2   foo    bar

In [10]:
data_for_one = {
    "First" : [5,6, "Hello"],
    "Second" : [7,8, "World"]
}

df_one = pd.DataFrame(data_for_one)

df_combined = pd.concat([df_one, df_two])

df_combined.reset_index(drop=True, inplace=True)

df_combined

   First Second
0      5      7
1      6      8
2  Hello  World
3      1      3
4      2      4
5    foo    bar

In [11]:
column_data = {
    "Third" : ["a", "b", "c"]
}

df_three = pd.DataFrame(column_data)

df_combined = pd.concat([df_combined, df_three], axis=1)

df_combined

   First Second Third
0      5      7     a
1      6      8     b
2  Hello  World     c
3      1      3   NaN
4      2      4   NaN
5    foo    bar   NaN