# Dealing with cetgorical data

In [1]:
# creating a dataframe with just the categorical features from our original dataframe

import pandas as pd

In [2]:
data_df = pd.read_csv("hotel_bookings.csv")

In [3]:
data_df = pd.DataFrame(data_df)

In [4]:
data_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [6]:
cat_cols = [col for col in data_df.columns if data_df[col].dtype=="object"]
cat_cols

['hotel',
 'arrival_date_month',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status',
 'reservation_status_date']

In [7]:
cat_df = data_df[cat_cols]
cat_df

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
1,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
2,Resort Hotel,July,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out,2015-07-02
3,Resort Hotel,July,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out,2015-07-02
4,Resort Hotel,July,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,August,BB,BEL,Offline TA/TO,TA/TO,A,A,No Deposit,Transient,Check-Out,2017-09-06
119386,City Hotel,August,BB,FRA,Online TA,TA/TO,E,E,No Deposit,Transient,Check-Out,2017-09-07
119387,City Hotel,August,BB,DEU,Online TA,TA/TO,D,D,No Deposit,Transient,Check-Out,2017-09-07
119388,City Hotel,August,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2017-09-07
119389,City Hotel,August,HB,DEU,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2017-09-07

In [9]:
# printing unique values of each column
for col in cat_df.columns:
    print(f"{col}: \n {cat_df[col].unique()}\n")

hotel:
 ['Resort Hotel' 'City Hotel']

arrival_date_month:
 ['July' 'August' 'September' 'October' 'November' 'December' 'January'
 'February' 'March' 'April' 'May' 'June']

meal:
 ['BB' 'FB' 'HB' 'SC' 'Undefined']

country:
 ['PRT' 'GBR' 'USA' 'ESP' 'IRL' 'FRA' nan 'ROU' 'NOR' 'OMN' 'ARG' 'POL'
 'DEU' 'BEL' 'CHE' 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST'
 'CZE' 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX' 'MAR'
 'UKR' 'SMR' 'LVA' 'PRI' 'SRB' 'CHL' 'AUT' 'BLR' 'LTU' 'TUR' 'ZAF' 'AGO'
 'ISR' 'CYM' 'ZMB' 'CPV' 'ZWE' 'DZA' 'KOR' 'CRI' 'HUN' 'ARE' 'TUN' 'JAM'
 'HRV' 'HKG' 'IRN' 'GEO' 'AND' 'GIB' 'URY' 'JEY' 'CAF' 'CYP' 'COL' 'GGY'
 'KWT' 'NGA' 'MDV' 'VEN' 'SVK' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'SEN'
 'SYC' 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MKD' 'MYS' 'ARM' 'JPN' 'LKA' 'CUB'
 'CMR' 'BIH' 'MUS' 'COM' 'SUR' 'UGA' 'BGR' 'CIV' 'JOR' 'SYR' 'SGP' 'BDI'
 'SAU' 'VNM' 'PLW' 'QAT' 'EGY' 'PER' 'MLT' 'MWI' 'ECU' 'MDG' 'ISL' 'UZB'
 'NPL' 'BHS' 'MAC' 'TGO' 'TWN' 'DJI' 'STP' 'KNA' 'ETH' 'IRQ' 'HND' 'RWA'
 'KHM' 'MCO' 'BGD' 'IMN' 'TJK' 'NIC' 'BEN' 'VGB' 'TZA' 'GAB' 'GHA' 'TMP'
 'GLP' 'KEN' 'LIE' 'GNB' 'MNE' 'UMI' 'MYT' 'FRO' 'MMR' 'PAN' 'BFA' 'LBY'
 'MLI' 'NAM' 'BOL' 'PRY' 'BRB' 'ABW' 'AIA' 'SLV' 'DMA' 'PYF' 'GUY' 'LCA'
 'ATA' 'GTM' 'ASM' 'MRT' 'NCL' 'KIR' 'SDN' 'ATF' 'SLE' 'LAO']

market_segment:
 ['Direct' 'Corporate' 'Online TA' 'Offline TA/TO' 'Complementary' 'Groups'
 'Undefined' 'Aviation']

distribution_channel:
 ['Direct' 'Corporate' 'TA/TO' 'Undefined' 'GDS']

reserved_room_type:
 ['C' 'A' 'D' 'E' 'G' 'F' 'H' 'L' 'P' 'B']

assigned_room_type:
 ['C' 'A' 'D' 'E' 'G' 'F' 'I' 'B' 'H' 'P' 'L' 'K']

deposit_type:
 ['No Deposit' 'Refundable' 'Non Refund']

customer_type:
 ['Transient' 'Contract' 'Transient-Party' 'Group']

reservation_status:
 ['Check-Out' 'Canceled' 'No-Show']

reservation_status_date:
 ['2015-07-01' '2015-07-02' '2015-07-03' '2015-05-06' '2015-04-22'
 '2015-06-23' '2015-07-05' '2015-07-06' '2015-07-07' '2015-07-08'
 '2015-05-11' '2015-07-15' '2015-07-16' '2015-05-29' '2015-05-19'
 '2015-06-19' '2015-05-23' '2015-05-18' '2015-07-09' '2015-06-02'
 '2015-07-13' '2015-07-04' '2015-06-29' '2015-06-16' '2015-06-18'
 '2015-06-12' '2015-06-09' '2015-05-26' '2015-07-11' '2015-07-12'
 '2015-07-17' '2015-04-15' '2015-05-13' '2015-07-10' '2015-05-20'
 '2015-05-12' '2015-07-14' '2015-06-17' '2015-05-01' '2015-03-30'
 '2015-07-19' '2015-06-03' '2015-06-26' '2015-05-14' '2015-07-20'
 '2015-05-07' '2015-05-28' '2015-04-13' '2015-03-25' '2015-07-21'
 '2015-06-27' '2015-07-18' '2015-07-23' '2015-06-08' '2015-06-22'
 '2015-06-24' '2015-03-05' '2015-06-01' '2015-04-24' '2015-07-22'
 '2015-05-27' '2015-04-06' '2015-04-11' '2015-07-25' '2015-07-28'
 '2015-07-29' '2015-06-25' '2015-07-24' '2015-06-05' '2015-06-30'
 '2015-06-13' '2015-06-11' '2015-07-30' '2015-07-27' '2015-04-29'
 '2015-06-04' '2015-07-26' '2015-08-01' '2015-08-02' '2015-06-15'
 '2015-04-23' '2015-07-31' '2015-05-25' '2015-08-03' '2015-04-17'
 '2015-08-04' '2015-08-06' '2015-05-15' '2015-05-09' '2015-03-17'
 '2015-05-22' '2015-08-07' '2015-04-04' '2015-08-05' '2015-08-08'
 '2015-08-10' '2015-05-04' '2015-06-06' '2015-08-09' '2015-08-15'
 '2015-08-11' '2015-03-28' '2015-08-14' '2015-08-12' '2015-08-16'
 '2015-05-16' '2015-08-21' '2015-08-13' '2015-08-17' '2015-04-20'
 '2015-08-18' '2015-08-23' '2015-08-22' '2015-08-19' '2015-08-20'
 '2015-08-29' '2015-03-31' '2015-05-30' '2015-08-25' '2015-04-14'
 '2015-08-24' '2015-03-24' '2015-05-21' '2015-08-28' '2015-08-26'
 '2015-08-27' '2015-08-30' '2015-08-31' '2015-09-06' '2015-09-03'
 '2015-09-04' '2015-09-02' '2015-09-01' '2015-09-05' '2015-06-20'
 '2015-09-07' '2015-09-10' '2015-09-11' '2015-09-08' '2015-09-09'
 '2015-09-13' '2015-09-15' '2015-04-10' '2015-01-02' '2014-11-18'
 '2015-09-12' '2015-09-17' '2015-09-14' '2015-04-07' '2015-09-19'
 '2015-09-16' '2015-09-20' '2015-01-18' '2015-10-23' '2015-01-22'
 '2015-01-01' '2015-09-22' '2015-09-24' '2015-09-18' '2015-09-21'
 '2015-09-30' '2015-09-25' '2015-09-27' '2015-09-28' '2015-10-12'
 '2015-09-29' '2015-09-23' '2015-10-01' '2015-09-26' '2015-04-18'
 '2015-10-02' '2015-10-04' '2015-10-08' '2015-10-03' '2015-10-07'
 '2015-10-09' '2015-10-11' '2015-10-05' '2015-10-06' '2015-10-10'
 '2015-10-14' '2015-10-15' '2015-10-18' '2015-10-13' '2015-10-20'
 '2015-10-19' '2015-10-31' '2015-10-16' '2015-10-21' '2015-10-22'
 '2015-10-17' '2015-10-24' '2015-10-25' '2015-10-28' '2015-10-27'
 '2015-10-26' '2015-10-30' '2015-11-05' '2015-10-29' '2015-11-03'
 '2015-11-07' '2015-11-04' '2015-11-01' '2015-11-02' '2015-11-17'
 '2015-11-06' '2015-11-10' '2015-11-08' '2015-11-09' '2015-11-15'
 '2015-11-16' '2015-11-11' '2015-11-12' '2015-11-14' '2015-11-13'
 '2015-11-18' '2015-11-22' '2015-11-19' '2015-11-21' '2015-11-20'
 '2015-11-24' '2015-11-25' '2015-11-23' '2015-11-28' '2015-11-26'
 '2015-11-27' '2015-11-29' '2015-12-04' '2015-12-01' '2015-12-06'
 '2015-12-08' '2015-12-02' '2015-12-03' '2015-12-31' '2015-12-05'
 '2015-12-10' '2015-12-17' '2015-11-30' '2015-12-12' '2015-12-07'
 '2016-01-05' '2015-12-11' '2015-12-13' '2015-12-15' '2015-12-16'
 '2015-12-19' '2015-12-18' '2015-12-26' '2015-12-27' '2015-12-22'
 '2015-12-23' '2015-12-24' '2015-12-29' '2015-12-28' '2015-12-20'
 '2015-12-30' '2016-01-02' '2016-01-01' '2015-12-25' '2016-01-03'
 '2016-01-04' '2016-01-11' '2016-01-07' '2015-12-21' '2016-01-09'
 '2016-01-10' '2016-01-08' '2016-01-06' '2016-01-12' '2016-01-13'
 '2016-01-23' '2016-02-09' '2016-01-15' '2016-01-16' '2016-01-17'
 '2016-01-19' '2016-01-18' '2016-01-21' '2016-01-24' '2016-01-22'
 '2016-01-29' '2016-01-27' '2016-01-25' '2016-03-08' '2016-01-26'
 '2016-01-20' '2016-01-30' '2016-02-01' '2016-02-02' '2016-02-08'
 '2016-02-07' '2016-01-28' '2016-02-05' '2016-02-03' '2016-02-13'
 '2016-02-10' '2016-02-04' '2016-02-12' '2016-02-11' '2016-02-16'
 '2016-02-14' '2016-02-15' '2016-02-20' '2016-02-06' '2016-01-14'
 '2016-02-17' '2016-02-21' '2016-02-24' '2016-02-25' '2016-02-19'
 '2016-02-18' '2016-02-26' '2016-02-23' '2016-03-05' '2016-02-22'
 '2016-02-27' '2016-03-03' '2016-03-24' '2016-03-04' '2016-02-29'
 '2016-03-01' '2016-03-02' '2016-03-30' '2016-03-07' '2016-03-14'
 '2016-03-21' '2016-03-09' '2016-03-12' '2016-03-22' '2016-03-10'
 '2016-03-11' '2016-03-20' '2016-03-15' '2016-03-17' '2016-03-16'
 '2016-03-19' '2016-03-27' '2016-03-18' '2016-03-26' '2016-03-31'
 '2016-03-28' '2016-03-29' '2016-04-01' '2016-03-23' '2016-04-02'
 '2016-03-25' '2016-03-13' '2016-04-04' '2016-04-03' '2016-04-05'
 '2016-04-08' '2016-04-06' '2016-04-09' '2016-04-12' '2016-04-16'
 '2016-04-17' '2016-04-27' '2016-04-14' '2016-04-18' '2016-04-21'
 '2016-04-19' '2016-04-20' '2016-04-10' '2016-04-13' '2016-04-11'
 '2016-04-07' '2016-04-15' '2016-04-22' '2016-04-23' '2016-04-26'
 '2016-04-28' '2016-04-24' '2016-04-25' '2016-04-29' '2016-04-30'
 '2016-05-01' '2016-05-10' '2016-05-02' '2016-05-07' '2016-05-08'
 '2016-05-12' '2016-05-04' '2016-05-06' '2016-05-03' '2016-05-09'
 '2016-05-05' '2016-05-13' '2016-05-14' '2016-05-18' '2016-05-19'
 '2016-05-15' '2016-05-16' '2016-05-11' '2016-05-21' '2016-05-22'
 '2016-05-20' '2016-05-24' '2016-05-25' '2016-05-26' '2016-05-23'
 '2016-05-27' '2016-05-17' '2016-05-29' '2016-05-28' '2016-05-30'
 '2016-05-31' '2016-06-01' '2016-06-03' '2016-06-08' '2016-06-02'
 '2016-06-05' '2016-06-06' '2016-06-13' '2016-06-07' '2016-06-10'
 '2016-06-11' '2016-06-16' '2016-06-12' '2016-06-14' '2016-06-17'
 '2016-06-04' '2016-06-18' '2016-06-21' '2016-06-09' '2016-06-24'
 '2016-06-20' '2016-06-25' '2016-06-22' '2016-06-26' '2016-06-23'
 '2016-07-01' '2016-06-15' '2016-06-28' '2016-07-02' '2016-06-19'
 '2016-06-27' '2016-07-04' '2016-06-30' '2016-07-05' '2016-07-08'
 '2016-07-09' '2016-07-07' '2016-07-12' '2016-06-29' '2016-07-10'
 '2016-07-15' '2016-07-03' '2016-07-16' '2016-07-14' '2016-07-18'
 '2016-07-13' '2016-07-06' '2016-07-20' '2016-07-21' '2016-07-23'
 '2016-07-19' '2016-07-11' '2016-07-28' '2016-07-17' '2016-07-25'
 '2016-07-22' '2016-07-29' '2016-08-03' '2016-08-02' '2016-08-04'
 '2016-08-08' '2016-08-10' '2016-08-01' '2016-08-06' '2016-03-06'
 '2016-08-05' '2016-07-26' '2016-08-07' '2016-07-30' '2016-07-24'
 '2016-08-12' '2016-07-27' '2016-08-13' '2016-08-18' '2016-08-16'
 '2016-08-15' '2016-08-17' '2016-08-11' '2016-07-31' '2016-08-19'
 '2016-09-01' '2016-08-23' '2016-08-26' '2016-08-20' '2016-08-21'
 '2016-09-04' '2016-08-22' '2016-08-27' '2016-08-25' '2016-08-09'
 '2016-09-05' '2016-08-24' '2016-09-10' '2016-08-29' '2016-09-09'
 '2016-08-30' '2016-09-13' '2016-08-31' '2016-09-14' '2016-09-12'
 '2016-09-15' '2016-08-14' '2016-09-02' '2016-09-08' '2016-09-19'
 '2016-09-16' '2016-09-07' '2016-09-21' '2016-09-06' '2016-09-22'
 '2016-09-17' '2016-09-20' '2016-09-03' '2016-09-26' '2016-09-23'
 '2016-09-18' '2016-09-29' '2016-10-02' '2016-10-01' '2016-09-27'
 '2016-09-25' '2016-10-05' '2016-09-11' '2016-09-30' '2016-10-09'
 '2016-10-03' '2016-10-06' '2016-10-11' '2016-09-24' '2016-10-13'
 '2016-09-28' '2016-10-08' '2016-10-07' '2016-10-16' '2016-08-28'
 '2016-10-17' '2016-10-18' '2016-10-10' '2016-10-04' '2016-10-15'
 '2016-10-19' '2016-10-21' '2016-10-12' '2016-10-24' '2016-10-26'
 '2016-10-23' '2016-10-20' '2016-10-25' '2016-10-27' '2016-10-28'
 '2016-10-30' '2016-10-29' '2016-11-01' '2016-11-04' '2016-10-14'
 '2016-11-07' '2016-11-03' '2016-11-10' '2016-11-14' '2016-11-02'
 '2016-10-31' '2016-11-11' '2016-11-08' '2016-11-05' '2016-11-25'
 '2016-11-09' '2016-11-20' '2016-11-21' '2016-10-22' '2016-11-22'
 '2016-11-16' '2016-11-23' '2016-11-17' '2016-11-06' '2016-11-15'
 '2016-11-13' '2016-11-12' '2016-11-27' '2016-11-19' '2016-11-30'
 '2016-11-18' '2016-12-02' '2016-12-04' '2016-11-29' '2016-12-07'
 '2016-11-28' '2016-12-03' '2016-12-06' '2016-11-24' '2016-12-08'
 '2016-12-05' '2016-12-10' '2016-12-13' '2016-12-14' '2016-12-16'
 '2016-12-15' '2016-12-17' '2016-12-19' '2016-12-21' '2016-12-20'
 '2016-12-22' '2016-12-23' '2016-12-24' '2016-12-01' '2016-12-27'
 '2016-12-29' '2016-12-30' '2016-12-12' '2017-01-02' '2016-12-11'
 '2017-01-03' '2017-01-04' '2017-01-01' '2016-12-26' '2017-01-06'
 '2016-12-28' '2016-12-18' '2017-01-10' '2017-01-11' '2017-01-07'
 '2017-01-12' '2017-01-16' '2017-01-14' '2017-01-13' '2017-01-05'
 '2017-01-17' '2017-01-20' '2016-12-09' '2017-01-26' '2016-12-31'
 '2017-01-23' '2017-01-27' '2017-01-28' '2017-01-19' '2017-01-25'
 '2017-01-24' '2017-01-29' '2017-01-18' '2016-12-25' '2017-01-15'
 '2017-01-21' '2017-02-01' '2017-02-02' '2017-01-31' '2017-02-03'
 '2017-02-04' '2017-02-06' '2017-02-07' '2017-02-08' '2017-01-30'
 '2017-02-09' '2017-01-09' '2017-02-11' '2017-02-10' '2017-02-12'
 '2017-02-13' '2017-02-14' '2017-02-16' '2017-02-17' '2017-02-18'
 '2017-02-19' '2017-02-20' '2017-02-15' '2017-02-21' '2017-02-22'
 '2017-02-26' '2017-02-23' '2017-02-24' '2017-02-25' '2017-02-28'
 '2017-03-05' '2017-02-27' '2017-03-03' '2017-03-06' '2017-03-02'
 '2017-03-08' '2017-03-09' '2017-03-10' '2017-03-07' '2017-03-12'
 '2017-03-13' '2017-03-14' '2017-03-01' '2017-03-18' '2017-03-17'
 '2017-03-24' '2017-03-22' '2017-03-26' '2017-03-27' '2017-03-11'
 '2017-03-28' '2017-03-29' '2017-03-30' '2017-03-31' '2017-03-19'
 '2017-01-22' '2017-04-02' '2017-03-20' '2017-04-03' '2017-01-08'
 '2017-03-23' '2017-04-05' '2017-02-05' '2017-04-04' '2017-03-15'
 '2017-04-07' '2017-03-25' '2017-04-08' '2017-04-06' '2017-03-21'
 '2017-04-10' '2017-04-01' '2017-04-11' '2017-04-13' '2017-04-15'
 '2017-04-12' '2017-03-04' '2017-04-19' '2017-04-22' '2017-04-20'
 '2017-05-02' '2017-04-09' '2017-04-23' '2017-04-24' '2017-04-16'
 '2017-04-28' '2017-04-18' '2017-04-26' '2017-04-25' '2017-04-17'
 '2017-04-21' '2017-05-03' '2017-05-04' '2017-03-16' '2017-05-05'
 '2017-04-29' '2017-04-14' '2017-05-08' '2017-04-27' '2017-05-11'
 '2017-05-01' '2017-05-10' '2017-05-13' '2017-05-06' '2017-05-14'
 '2017-05-16' '2017-04-30' '2017-05-15' '2017-05-07' '2017-05-09'
 '2017-05-17' '2017-05-21' '2017-05-12' '2017-05-22' '2017-05-24'
 '2017-05-23' '2017-05-25' '2017-05-26' '2017-05-28' '2017-05-27'
 '2017-05-29' '2017-05-19' '2017-05-31' '2017-05-20' '2017-06-01'
 '2017-05-30' '2017-06-02' '2016-11-26' '2017-06-04' '2017-06-05'
 '2017-06-06' '2017-06-07' '2017-05-18' '2017-06-09' '2017-06-10'
 '2017-06-11' '2017-06-12' '2017-06-14' '2017-06-08' '2017-06-16'
 '2017-06-13' '2017-06-03' '2017-06-24' '2017-06-20' '2017-06-19'
 '2017-06-21' '2017-06-26' '2017-06-27' '2017-06-22' '2017-06-28'
 '2017-06-15' '2017-06-29' '2017-06-30' '2017-06-18' '2017-07-04'
 '2017-07-08' '2017-07-05' '2017-07-03' '2017-07-07' '2017-07-01'
 '2017-07-06' '2017-07-11' '2017-07-12' '2017-06-23' '2017-07-13'
 '2017-07-02' '2017-07-10' '2017-07-14' '2017-07-15' '2017-07-16'
 '2017-07-18' '2017-07-17' '2017-07-19' '2017-07-20' '2017-07-21'
 '2017-06-25' '2017-06-17' '2017-07-24' '2017-07-26' '2017-07-09'
 '2017-07-27' '2017-07-28' '2017-07-31' '2017-07-29' '2017-07-22'
 '2017-08-02' '2017-08-01' '2017-08-03' '2017-08-04' '2017-07-25'
 '2017-07-23' '2017-08-09' '2017-08-10' '2017-07-30' '2017-08-07'
 '2017-08-13' '2017-08-05' '2017-08-14' '2017-08-08' '2017-08-16'
 '2017-08-17' '2017-08-15' '2017-08-18' '2017-08-20' '2017-08-22'
 '2017-08-06' '2017-08-25' '2017-08-26' '2017-08-23' '2017-08-11'
 '2017-08-27' '2017-08-21' '2017-08-29' '2017-08-31' '2017-08-12'
 '2017-08-19' '2016-01-31' '2017-09-01' '2017-08-28' '2015-04-03'
 '2015-01-21' '2015-01-28' '2015-01-29' '2015-01-30' '2015-02-02'
 '2015-02-05' '2015-02-06' '2015-02-09' '2015-02-10' '2015-02-11'
 '2015-02-12' '2015-02-19' '2015-02-20' '2015-02-23' '2015-02-24'
 '2015-02-25' '2015-02-26' '2015-02-27' '2015-03-03' '2015-03-04'
 '2015-03-06' '2015-03-09' '2015-03-11' '2015-03-12' '2015-03-18'
 '2015-04-02' '2015-06-14' '2015-04-08' '2015-04-16' '2015-04-25'
 '2015-04-28' '2015-05-08' '2017-09-06' '2016-02-28' '2015-12-09'
 '2015-12-14' '2017-09-09' '2017-09-02' '2017-08-24' '2017-08-30'
 '2017-09-03' '2017-09-04' '2017-09-05' '2017-09-07' '2017-09-08'
 '2017-09-10' '2017-09-12' '2017-09-14' '2015-04-30' '2015-04-21'
 '2015-04-05' '2015-03-13' '2015-05-05' '2015-03-29' '2015-06-10'
 '2015-04-27' '2014-10-17' '2015-01-20' '2015-02-17' '2015-03-10'
 '2015-03-23']

In [10]:
cat_df["arrival_date_month"] = cat_df["arrival_date_month"].map({"January":1, "February":2, "March":3, "April":4, "May":5, "June":6, "July":7, "August":8, "September":9, "October":10, "November":11, "December":12})

C:\Users\robfr\AppData\Local\Temp\ipykernel_2688\2131857715.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_df["arrival_date_month"] = cat_df["arrival_date_month"].map({"January":1, "February":2, "March":3, "April":4, "May":5, "June":6, "July":7, "August":8, "September":9, "October":10, "November":11, "December":12})

In [11]:
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,7,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
1,Resort Hotel,7,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
2,Resort Hotel,7,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out,2015-07-02
3,Resort Hotel,7,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out,2015-07-02
4,Resort Hotel,7,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-07-03

In [12]:
# country and hotel features

from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()

# label encoding country

cat_df["country"] = le.fit_transform(cat_df["country"])

# label encoding hotel

cat_df["hotel"] = le.fit_transform(cat_df["hotel"])

C:\Users\robfr\AppData\Local\Temp\ipykernel_2688\2811991337.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_df["country"] = le.fit_transform(cat_df["country"])
C:\Users\robfr\AppData\Local\Temp\ipykernel_2688\2811991337.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_df["hotel"] = le.fit_transform(cat_df["hotel"])

In [14]:
cat_df

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
0,1,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
1,1,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
2,1,7,BB,59,Direct,Direct,A,C,No Deposit,Transient,Check-Out,2015-07-02
3,1,7,BB,59,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out,2015-07-02
4,1,7,BB,59,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,8,BB,15,Offline TA/TO,TA/TO,A,A,No Deposit,Transient,Check-Out,2017-09-06
119386,0,8,BB,56,Online TA,TA/TO,E,E,No Deposit,Transient,Check-Out,2017-09-07
119387,0,8,BB,43,Online TA,TA/TO,D,D,No Deposit,Transient,Check-Out,2017-09-07
119388,0,8,BB,59,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2017-09-07
119389,0,8,HB,43,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2017-09-07

In [15]:
# one-hot encoding
cat_df = pd.get_dummies(data=cat_df, columns=["meal", "market_segment", "distribution_channel", "reserved_room_type", "assigned_room_type", "customer_type", "deposit_type", "reservation_status"])

In [16]:
cat_df

,hotel,arrival_date_month,country,reservation_status_date,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,...,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,1,7,135,2015-07-01,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
1,1,7,135,2015-07-01,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
2,1,7,59,2015-07-02,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
3,1,7,59,2015-07-02,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
4,1,7,59,2015-07-03,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,8,15,2017-09-06,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
119386,0,8,56,2017-09-07,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
119387,0,8,43,2017-09-07,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
119388,0,8,59,2017-09-07,True,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,False
119389,0,8,43,2017-09-07,False,False,True,False,False,False,...,False,False,True,False,True,False,False,False,True,False

In [17]:
# numerical dataframe
num_df = data_df.drop(columns=cat_cols, axis=1)

In [18]:
num_df

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,0,342,2015,27,1,0,0,2,0.0,0,0,0,0,3,NaN,NaN,0,0.00,0,0
1,0,737,2015,27,1,0,0,2,0.0,0,0,0,0,4,NaN,NaN,0,0.00,0,0
2,0,7,2015,27,1,0,1,1,0.0,0,0,0,0,0,NaN,NaN,0,75.00,0,0
3,0,13,2015,27,1,0,1,1,0.0,0,0,0,0,0,304.0,NaN,0,75.00,0,0
4,0,14,2015,27,1,0,2,2,0.0,0,0,0,0,0,240.0,NaN,0,98.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,2017,35,30,2,5,2,0.0,0,0,0,0,0,394.0,NaN,0,96.14,0,0
119386,0,102,2017,35,31,2,5,3,0.0,0,0,0,0,0,9.0,NaN,0,225.43,0,2
119387,0,34,2017,35,31,2,5,2,0.0,0,0,0,0,0,9.0,NaN,0,157.71,0,4
119388,0,109,2017,35,31,2,5,2,0.0,0,0,0,0,0,89.0,NaN,0,104.40,0,0
119389,0,205,2017,35,29,2,7,2,0.0,0,0,0,0,0,9.0,NaN,0,151.20,0,2

In [20]:
final_df = pd.concat([num_df, cat_df], axis=1)

In [21]:
# Correlation Analysis

# create a correlation matrix

corr_matrix = final_df.corr().abs()
corr_matrix

ValueError: could not convert string to float: '2015-07-01'